import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.HttpURLConnection;
import java.net.URL;
import javax.swing.table.DefaultTableModel;
import org.json.JSONObject;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Fadil
 */
public class CekCuaca extends javax.swing.JFrame {
    private javax.swing.JTable dataTable;
    private javax.swing.JScrollPane scrollPane;
    /**
     * Creates new form CekCuaca
     */
    public CekCuaca() {
        initComponents();
        dataTable = new JTable(new DefaultTableModel(new Object[]{"Kota", "Kondisi Cuaca"}, 0));
        scrollPane = new JScrollPane(dataTable);

                // Tambahkan ItemListener ke JComboBox untuk mendeteksi perubahan pilihan
        cmbfav.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                if (e.getStateChange() == ItemEvent.SELECTED) {
                    String selectedCity = (String) cmbfav.getSelectedItem();
                    kota.setText(selectedCity);  // Set kota text field dengan pilihan dari combo box
                    System.out.println("Kota favorit dipilih: " + selectedCity);
                }
            }
        });
    }
    private void updateWeatherIcon(String condition) {
    String iconPath = "/images/default.png";
    
    switch (condition.toLowerCase()) {
        case "clear":
        case "sunny":
            iconPath = "/images/sunny.png";
            break;
        case "rain":
        case "rainy":
        case "patchy rain nearby":
        case "showers":
        case "patchy light rain":
        case "moderate rain at times":
            iconPath = "/images/rainy.png";
            break;
        case "cloudy":
        case "overcast":
        case "partly cloudy":
            iconPath = "/images/cloudy.png";
            break;
        case "thunderstorm":
        case "patchy light rain with thunder":
        case "light rain shower":
        case "storm":
            iconPath = "/images/thunderstorm.png";
            break;
        default:
            iconPath = "/images/default.png";
            break;
    }
    
    gambar.setIcon(new ImageIcon(getClass().getResource(iconPath)));
}
    private boolean kotaAdaDiComboBox(String kota) {
    for (int i = 0; i < cmbfav.getItemCount(); i++) {
        if (cmbfav.getItemAt(i).equalsIgnoreCase(kota)) {
            return true;
        }
    }
    return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kota = new javax.swing.JTextField();
        lblhasil = new javax.swing.JLabel();
        btncekcuaca = new javax.swing.JButton();
        btnsimpanfav = new javax.swing.JButton();
        btnsimpandata = new javax.swing.JButton();
        btnmuatdata = new javax.swing.JButton();
        gambar = new javax.swing.JLabel();
        cmbfav = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblmuatdata = new javax.swing.JTable();
        btnkeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));

        lblhasil.setText("Kondisi Cuaca");

        btncekcuaca.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btncekcuaca.setText("Cek Cuaca");
        btncekcuaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncekcuacaActionPerformed(evt);
            }
        });

        btnsimpanfav.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnsimpanfav.setText("Simpan Favorit");
        btnsimpanfav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanfavActionPerformed(evt);
            }
        });

        btnsimpandata.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnsimpandata.setText("Simpan Data");
        btnsimpandata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpandataActionPerformed(evt);
            }
        });

        btnmuatdata.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnmuatdata.setText("Muat Data");
        btnmuatdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmuatdataActionPerformed(evt);
            }
        });

        cmbfav.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmbfav.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jakarta", "Bandung", "Semarang" }));

        tblmuatdata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kota ", "Kondisi Cuaca"
            }
        ));
        jScrollPane1.setViewportView(tblmuatdata);

        btnkeluar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnkeluar.setText("Keluar");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnkeluar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(gambar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnmuatdata)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(kota, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btncekcuaca, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblhasil))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnsimpanfav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnsimpandata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(cmbfav, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncekcuaca)
                    .addComponent(cmbfav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsimpanfav))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblhasil)
                    .addComponent(btnsimpandata))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gambar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnmuatdata)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnkeluar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncekcuacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncekcuacaActionPerformed
        // Ambil input kota dari JTextField atau dari pilihan JComboBox
        String city = kota.getText();
        
        // Panggil method getWeather dan ambil data cuaca
        String weatherCondition = CuacaClass.getWeather(city);
        
        // Tampilkan kondisi cuaca di JLabel
        lblhasil.setText("Kondisi Cuaca : " + weatherCondition);
        
        // Update gambar berdasarkan kondisi cuaca
        updateWeatherIcon(weatherCondition);
    }//GEN-LAST:event_btncekcuacaActionPerformed

    private void btnsimpanfavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanfavActionPerformed
        String kotaFavorit = kota.getText();
        if (!kotaFavorit.isEmpty() && !kotaAdaDiComboBox(kotaFavorit)) {
            cmbfav.addItem(kotaFavorit);
            System.out.println("Kota " + kotaFavorit + " ditambahkan ke favorit.");
        } else {
            System.out.println("Kota sudah ada di favorit atau input kosong.");
    }                                   
    }//GEN-LAST:event_btnsimpanfavActionPerformed

    private void btnsimpandataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpandataActionPerformed
        try (PrintWriter writer = new PrintWriter(new File("dataCuaca.csv"))) {
            writer.println("Kota, Kondisi Cuaca");
            String city = kota.getText();
            String weatherCondition = lblhasil.getText().replace("Kondisi Cuaca : ", "");
            writer.println(city + ", " + weatherCondition);
            JOptionPane.showMessageDialog(null, "Data cuaca berhasil disimpan ke CSV");
        } catch (Exception ex) {
            ex.printStackTrace();
    }                             
    }//GEN-LAST:event_btnsimpandataActionPerformed

    private void btnmuatdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmuatdataActionPerformed
    DefaultTableModel model = (DefaultTableModel) tblmuatdata.getModel();

    try (BufferedReader br = new BufferedReader(new FileReader("dataCuaca.csv"))) {
        String line;
        while ((line = br.readLine()) != null) {
            if (line.startsWith("Kota")) continue; // Skip header row

            String[] data = line.split(",");
            model.addRow(data); // Add data to the table without clearing it
        }
        JOptionPane.showMessageDialog(null, "Data berhasil dimuat dari CSV");
    } catch (Exception ex) {
        ex.printStackTrace();
    }                           
    }//GEN-LAST:event_btnmuatdataActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnkeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CekCuaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CekCuaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CekCuaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CekCuaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CekCuaca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncekcuaca;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnmuatdata;
    private javax.swing.JButton btnsimpandata;
    private javax.swing.JButton btnsimpanfav;
    private javax.swing.JComboBox<String> cmbfav;
    private javax.swing.JLabel gambar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kota;
    private javax.swing.JLabel lblhasil;
    private javax.swing.JTable tblmuatdata;
    // End of variables declaration//GEN-END:variables
}
